### ISSUE TITLE
Bank Account Dynamic Satellite

### ISSUE THREAD

**Issue by chrishombach** [montrek-software/montrek#10]
A dynamic Bank account satellite with attribute value, which is the sum of all the bank accounts values. 

## To-Do
- [x] Add Institute
    - [x] Add InstituteHub
    - [x] Add InstituteStaticSatellite
    - [x] Add AccountInstituteLink
    - [x] Add InstituteName to Account View
    - [x] Add to template
- [ ] Add IBAN
- [x] New bankaccount
- [x] Add functional tests
